### ISSUE TITLE
404: Not found in all yaml files

### ISSUE THREAD

**Issue by maxcroy1** [catppuccin/warp#10]
I recently tried to install these themes on my personal computer, and when I investigated further after the themes didn't show up in warp, I noticed that all files only had "404: Not Found" in them. 

Is this a me issue? Or something else?

**Comment by maxcroy1** [comment]
To clarify, this is what I'm seeing in each file:
![image](https://github.com/catppuccin/warp/assets/16827693/fd3b8622-5a7b-47f5-b374-f4b3b3819990)

**Comment by sgoudham** [comment]
Ah sorry did you use the curl commands on the README? I think we forgot to merge #9 for it to be accurate as we recently refactored the port!

**Comment by maxcroy1** [comment]
Ah seeing that update now! Resolved on my end :) Super impressed by your fast response time, thanks for reaching out!
