### ISSUE TITLE
404 not found.

### ISSUE THREAD

**Issue by chenzesam** [catppuccin/warp#2]

**Comment by chenzesam** [comment]
When i curl https://raw.githubusercontent.com/catppuccin/warp/main/dist/catppuccin_\{latte,frappe,macchiato,mocha\}.yml, it will show "Failed to connect to xxx", and open it by browser will show 404.

**Comment by nekowinston** [comment]
My bad, I changed the docs to list all flavors explicitly instead of relying on shell expansion. Those should work for you if you copy & paste.
