### ISSUE TITLE
Different theme location in Linux

### ISSUE THREAD

**Issue by t0msk** [catppuccin/warp#5]
In Linux it should be `${XDG_DATA_HOME:-$HOME/.local/share}/warp-terminal/themes/` and not `~/.warp/themes/` according to https://docs.warp.dev/appearance/custom-themes

**Comment by nekowinston** [comment]
Thanks, I gave this a try yesterday and meant to update the instructions, but wasn't able to update the README yet, i'd appreciate a PR.

**Comment by t0msk** [comment]
created https://github.com/catppuccin/warp/pull/6

**Comment by nekowinston** [comment]
Forgot to close via #6
